### ISSUE TITLE
Support for the stock Pico?

### ISSUE THREAD

**Issue by modeler** [robinhedwards/A8PicoCart#15]
Curious to know if the stock RPi Pico (green PCB with MicroUSB) is expected to work with this board, albeit with reduced capabilities? I'm assuming not, as I have built one and there is no splash screen, just a solid colour when powering on.

I don't have any other cartridge to test with my Atari 800 XL, so just wanted to confirm. Thanks!

**Comment by robinhedwards** [comment]
No - please don't try this, you'll be lucky not to break either the pico and/or your Atari 800XL, because the pinout of the two boards is quite different.

The stock/official RPi Pico doesn't break out enough of the RP2040 GPIO pins to fully connect the cartridge port, which is the main reason I chose the purple clone as a basis for this project.

Its possible to do a reduced version of the functionality with official green RPi pico (e.g. 8k cartridges), but you'd need to update both the firmware and the PCB design.

**Comment by modeler** [comment]
Thanks for the quick reply and detailed explanation Robin. Might it be worth adding a note in the README to this effect? I do not have an issue with the fact that is does not work, but the potential to damage an Atari is a concern. I would not want this to come across as any sort of criticism, I fully appreciate that you shared this project with the world for free, and my misinterpretation of it is not your issue.

**Comment by robinhedwards** [comment]
Thanks - I have added a note to the README as suggested. Hope your Atari is ok! Drop me a line if not, and I can probably help, since I had to replace the MMU on my own 65XE when I broke it during some early cartridge experiments.

**Comment by modeler** [comment]
Thank you! It's still passing the self test but I'll keep you posted. I'm not an Atari expert, I've repaired countless Commodore 64s and own a stack of them including two I built from scratch, but I only have the one Atari 8-bit machine.
